name: Update Packagist

on:
  push:
    tags:
      - 'v*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packagist Update
        run: |
          curl -XPOST -H'Content-Type: application/json' \
            'https://packagist.org/api/update-package?username=alex-kassel&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
            -d '{"repository":{"url":"https://github.com/alex-kassel/stable-fingerprint"}}'
